ctak/ctak/urls.py
from django.conf.urls import patterns, include, url
from ctak import settings
from django.contrib import admin
from .views import IndexDelete
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'ctak.views.home', name='home'),
    url(r'^newindex/$', 'ctak.views.newindex', name='newindex'),
    url(r'^indexmanage/$', 'ctak.views.indexmanage', name='indexmanage'),
    url(r'^ctak/(?P<pk>\d+)/delete/$', IndexDelete.as_view(), name='indexdelete'),
    url(r'^bay/lay/good/though/mode/duck/low/$', 'account.views.reg', name='reg'),
    url(r'^success/$', 'ctak.views.success', name='success'),
    url(r'^account/', include('account.urls')),
    url(r'^qr/', include('qrmaker.urls')),
    url(r'^html/', include('html.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATICFILES_DIRS}),
    # url(r'^admin/', include(admin.site.urls)),
)

ctak/ctak/models.py
from account.models import Producer
from django.db import models

class Index(models.Model):
    project = models.CharField(max_length=50)
    owner = models.ForeignKey(Producer)
    url = models.CharField(max_length=100)
    types = (('Django', 'Django'), ('html', 'html'),)
    type = models.CharField(max_length=20, choices=types)

    def __unicode__(self):
        return self.name

ctak/templates/base/base.html
<!DOCTYPE html>
<html class=no-js>
<head>
<meta charset=utf-8>
<title>打電話問功夫</title>
<meta name=description content="">
<meta name=viewport content="width=device-width"><link rel="shortcut icon" href={{MEDIA_URL}}webicon/2444b451.favicon.ico><!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
<link rel=stylesheet href={{STATIC_URL}}styles/dfc57042.vendor.css>
<link rel=stylesheet href={{STATIC_URL}}styles/a5896f90.main.css><body style="background-color: #E4D35B"><!--[if lt IE 10]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
<div class=header>{% include 'base/nav_bar.html' %}</div>
<div class=container style="max-width: 900px;background-color: #D3C58F">
    <div align=center>
        <b style=font-size:300%>
        {% block title %}{% endblock %}
        </b>
        <br>
        {% block content %}{% endblock %}
        <br>
    </div>
    <div class="row marketing" align=center>
    	{% block list %}{% endblock %}
    </div>
    <div align=center>
    	<b>{% block foot %}{% endblock %}</b>
    </div>
    <div class=footer>
    	<p align=center>
    		<span class="glyphicon glyphicon-heart"></span>
    		<b>本項目地址：<a href="https://github.com/Call-to-Ask-Kung-Fu/ctak" target="_blank">https://github.com/Call-to-Ask-Kung-Fu/ctak</a></b>
    	</p>
    </div>
</div>
<script src={{STATIC_URL}}scripts/4776dee8.vendor.js></script><!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
</script>
<script src={{STATIC_URL}}scripts/c6b52431.plugins.js></script>
<script src={{STATIC_URL}}scripts/b6c3df09.main.js></script>

ctak/templates/base/goback.html
<script type="text/javascript">
function goBack()
  {window.history.go(-1)}  
</script>
<input type="button" value="Back" onclick="goBack()" />

ctak/templates/base/nav_bar.html
<ul class="nav nav-pills pull-right" style="background-color: #F69C3A;">
	{% if user.is_authenticated %}	
	<li>		
		<a href="{% url 'producer_detail' %}" class="navbar-brand">早晨，{{ user.producer.nickname }}！</a>
	</li>
	<li>		
		<a href="{% url 'logout' %}">登出</a>
	</li>	
		{% else %}
	<li>
		<a href="{% url 'login' %}" class="navbar-brand">登錄</a>
		{% endif %}
	</li>
	<li class=dropdown>
		<a href=# class=dropdown-toggle data-toggle=dropdown>頁面項目管理</a>
		<ul class=dropdown-menu>
			<li><a href="{% url 'newproject' %}">上傳新嘢</a></li>
			<li><a href="{% url 'projectmanage' %}">刪舊嘢</a></li>
		</ul>
	</li>
	<li class=dropdown>
		<a href=# class=dropdown-toggle data-toggle=dropdown>Django App管理</a>
		<ul class=dropdown-menu>
		<li><a href="{% url 'newindex' %}">新增App鏈接</a></li>
		<li><a href="{% url 'indexmanage' %}">刪除APP鏈接</a></li>	

		</ul>
	</li>
	{% for i in navlist %}
	<li class=dropdown>
		<a href=# class=dropdown-toggle data-toggle=dropdown>{{ i.nickname }}</a>
		<ul class=dropdown-menu>
			{% for p in i.index_set.all %}
			<li><a href="{{ p.url }}">{{ p.project }}</a></li>
			{% endfor %}
			<li class=divider></li>
			<li><a href="/account/{{ i.id }}">睇傻蟹</a></li>
		</ul>
	</li>
	{% endfor %}
	
	
	<li><a href="{% url 'home' %}">回到首頁</a></li>
</ul>
<h3 class=text-danger style="padding-left: 25px;">打電話問功夫</h3>